/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: 0.3.0
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type CreateEksPropertiesEksMaster struct {
	InstanceType string `json:"instanceType,omitempty"`
	// You can find latest images here: https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
	Image string `json:"image,omitempty"`
}
