/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments.
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type SpotguideOption struct {
	Name     string `json:"name,omitempty"`
	Type     string `json:"type,omitempty"`
	Info     string `json:"info,omitempty"`
	Default  string `json:"default,omitempty"`
	Readonly bool   `json:"readonly,omitempty"`
	Key      string `json:"key,omitempty"`
}
