/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: 0.3.0
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

type ClusterProfileEksEks struct {
	Version   string                     `json:"version,omitempty"`
	NodePools map[string]NodePoolsAmazon `json:"nodePools,omitempty"`
}
