/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: 0.3.0
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type SpotguideDetailsResponse struct {
	Name      string                            `json:"name,omitempty"`
	CreatedAt string                            `json:"createdAt,omitempty"`
	UpdatedAt string                            `json:"updatedAt,omitempty"`
	Spotguide SpotguideDetailsResponseSpotguide `json:"spotguide,omitempty"`
	Questions map[string]interface{}            `json:"questions,omitempty"`
}
