/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: 0.3.0
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type PodItemLabels struct {
	App     string `json:"app,omitempty"`
	Chart   string `json:"chart,omitempty"`
	Release string `json:"release,omitempty"`
}
