/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: 0.3.0
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type NodeItemMetadataAnnotations struct {
	NodeAlphaKubernetesIottl string `json:"node.alpha.kubernetes.io/ttl,omitempty"`
	VolumesKubernetesIocontrollerManagedAttachDetach string `json:"volumes.kubernetes.io/controller-managed-attach-detach,omitempty"`
}
