apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipeline.fullname" . }}
  labels:
    {{ include "pipeline.labels" . | nindent 4 }}
data:
  config.yaml: |
   {{ toYaml .Values.configuration | nindent 4 }}
