{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pipeline.serviceAccountName" . }}
  labels:
    {{ include "pipeline.labels" . | nindent 4 }}
{{ end }}
