apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipeline.fullname" . }}-ssh
  labels:
    app: {{ include "pipeline.name" . }}
    chart: {{ template "pipeline.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data: {}