apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipeline.fullname" . }}
  labels:
    {{ include "pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  clientId: {{ default .Values.configuration.auth.oidc.clientId .Values.configuration.auth.oidc.clientId | b64enc | quote }}
  clientSecret: {{ default .Values.configuration.auth.oidc.clientSecret .Values.configuration.auth.oidc.clientSecret | b64enc | quote }}
  tokenSigningKey: {{ default .Values.configuration.auth.oidc.clientSecret .Values.configuration.auth.token.signingKey | b64enc | quote }}

---
{{ if not .Values.service.tls.secretName }}
{{- $cn := include "pipeline.fullname" . -}}
{{- $externalDNS := print $cn "." .Release.Namespace -}}
{{- $ca := genCA "pipeline-ca" 365 -}}
{{- $cert := genSignedCert $cn (list "127.0.0.1") (list $cn $externalDNS) 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipeline-tls-secret-name" . }}
  labels:
    {{ include "pipeline.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{ end }}

{{ if .Values.configuration.database.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pipeline.fullname" . }}-database
  labels:
    {{ include "pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.configuration.database.password | b64enc | quote }}
{{ end }}
