apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeline.fullname" . }}
  labels:
    {{ include "pipeline.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    # https://github.com/containous/traefik/issues/3806
    name: "https-{{ .Values.service.name }}"
  {{- if .Values.metrics.enabled }}
  - port: {{ .Values.metrics.port }}
    targetPort: {{ .Values.metrics.port }}
    protocol: TCP
    name: "metrics"
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "pipeline.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
