apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeline.fullname" . }}
  labels:
    app: {{ include "pipeline.name" . }}
    chart: {{ template "pipeline.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
  {{- if .Values.service.tls  }}
#https://github.com/containous/traefik/issues/3806
    name: "https-{{ .Values.service.name }}"
  {{- else }}
    name: "{{ .Values.service.name }}"
  {{ end }}
  selector:
    app: {{ include "pipeline.name" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeline.fullname" . }}-internal
  labels:
    app: {{ include "pipeline.name" . }}
    chart: {{ template "pipeline.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceInternal.type }}
  ports:
  - port: {{ .Values.serviceInternal.externalPort }}
    targetPort: {{ .Values.serviceInternal.internalPort }}
    protocol: TCP
  {{- if .Values.serviceInternal.tls  }}
#https://github.com/containous/traefik/issues/3806
    name: "https-{{ .Values.serviceInternal.name }}"
  {{- else }}
    name: "{{ .Values.serviceInternal.name }}"
  {{ end }}
  selector:
    app: {{ include "pipeline.name" . }}