{{- if and .Values.statestore.persistence.enabled (not .Values.statestore.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "pipeline.fullname" . }}-statestore
  labels:
    app: {{ include "pipeline.name" . }}
    chart: {{ template "pipeline.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.statestore.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.statestore.persistence.size | quote }}
{{- if .Values.statestore.persistence.storageClass }}
{{- if (eq "-" .Values.statestore.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.statestore.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
