// Code generated by mockery v1.0.0. DO NOT EDIT.

package cluster

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockDynamicFileClientFactory is an autogenerated mock type for the DynamicFileClientFactory type
type MockDynamicFileClientFactory struct {
	mock.Mock
}

// FromSecret provides a mock function with given fields: ctx, secretID
func (_m *MockDynamicFileClientFactory) FromSecret(ctx context.Context, secretID string) (DynamicFileClient, error) {
	ret := _m.Called(ctx, secretID)

	var r0 DynamicFileClient
	if rf, ok := ret.Get(0).(func(context.Context, string) DynamicFileClient); ok {
		r0 = rf(ctx, secretID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(DynamicFileClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, secretID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
