swagger: '2.0'
info:
  description: Pipeline v0.3.0 swagger
  version: "0.3.0"
  title: Pipeline Internal API
  contact:
    email: info@banzaicloud.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/notifications':
    get:
      description: Lists all notifications
      produces:
        - application/json
      schemes:
        - http
      operationId: GetNotifications
      responses:
        '200':
          description: GetNotificationsResponse
          schema:
            $ref: '#/definitions/GetNotificationsResponse'
  '/dashboard/{orgid}/clusters':
    get:
      description: Returns returns dashboard metrics for selected/all clusters of an organization
      produces:
        - application/json
      schemes:
        - http
      tags:
        - orgid
      operationId: GetDashboard
      parameters:
        - type: string
          x-go-name: OrgId
          name: orgid
          in: path
          required: true
      responses:
        '200':
          description: GetDashboardResponse
          schema:
            $ref: '#/definitions/GetDashboardResponse'
  '/issues':
    post:
      description: Creates a new issue in the configured issue tracking system.
      schemes:
        - http
      operationId: CreateIssue
      parameters:
        - in: body
          name: user
          description: The issue to create.
          schema:
            type: object
            required:
              - organization
              - title
              - text
            properties:
              organization:
                type: string
              title:
                type: string
              text:
                type: string
              labels:
                type: array
                items:
                  type: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Issue Creation Failed
definitions:
  Allocatable:
    type: object
    properties:
      cpu:
        type: string
        x-go-name: Cpu
      ephemeralStorage:
        type: string
        x-go-name: EphemeralStorage
      memory:
        type: string
        x-go-name: Memory
      pods:
        type: integer
        format: int64
        x-go-name: Pods
    x-go-package: github.com/banzaicloud/pipeline/internal/dashboard
  Capacity:
    type: object
    properties:
      cpu:
        type: string
        x-go-name: Cpu
      ephemeralStorage:
        type: string
        x-go-name: EphemeralStorage
      memory:
        type: string
        x-go-name: Memory
      pods:
        type: integer
        format: int64
        x-go-name: Pods
    x-go-package: github.com/banzaicloud/pipeline/internal/dashboard
  Cluster:
    type: object
    properties:
      cloud:
        type: string
        x-go-name: Cloud
      cpuUsagePercent:
        type: number
        format: double
        x-go-name: CpuUsagePercent
      createdAt:
        type: string
        x-go-name: CreatedAt
      id:
        type: string
        x-go-name: Id
      memoryUsagePercent:
        type: number
        format: double
        x-go-name: MemoryUsagePercent
      name:
        type: string
        x-go-name: Name
      distribution:
        type: string
        x-go-name: Distribution
      nodes:
        type: array
        items:
          $ref: '#/definitions/Node'
        x-go-name: Nodes
      region:
        type: string
        x-go-name: Region
      status:
        type: string
        x-go-name: Status
      statusMessage:
        type: string
        x-go-name: StatusMessage
      storageUsagePercent:
        type: number
        format: double
        x-go-name: StorageUsagePercent
    x-go-package: github.com/banzaicloud/pipeline/internal/dashboard
  GetDashboardPathParams:
    description: GetProviderPathParams is a placeholder for the providers related route path parameters
    type: object
    properties:
      orgid:
        description: 'in:path'
        type: string
        x-go-name: OrgId
    x-go-package: github.com/banzaicloud/pipeline/internal/dashboard
  GetNotificationsResponse:
    description: GetNotificationsResponse Api object to be mapped to Get notifications request
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/MessagesResponse'
        x-go-name: Messages
    x-go-package: github.com/banzaicloud/pipeline/internal/notification
  MessagesResponse:
    type: object
    properties:
      id:
        type: integer
        x-go-name: Id
      message:
        type: string
        x-go-name: Message
      priority:
        description: Severity of the notifications
        type: integer
        x-go-name: Priority
    x-go-package: github.com/banzaicloud/pipeline/internal/notification
  GetDashboardResponse:
    description: GetDashboardResponse Api object to be mapped to Get dashboard request
    type: object
    properties:
      clusters:
        type: array
        items:
          $ref: '#/definitions/Cluster'
        x-go-name: Clusters
    x-go-package: github.com/banzaicloud/pipeline/internal/dashboard
  Node:
    type: object
    properties:
      creationTimestamp:
        type: string
        x-go-name: CreationTimestamp
      name:
        type: string
        x-go-name: Name
      status:
        $ref: '#/definitions/Status'
    x-go-package: github.com/banzaicloud/pipeline/internal/dashboard
  Status:
    type: object
    properties:
      diskPressure:
        type: string
      frequentUnregisterNetDevice:
        type: string
      kernelDeadlock:
        type: string
      memoryPressure:
        type: string
      networkUnavailable:
        type: string
      outOfDisk:
        type: string
      pidPressure:
        type: string
      allocatable:
        $ref: '#/definitions/Allocatable'
      capacity:
        $ref: '#/definitions/Capacity'
      cpuUsagePercent:
        type: number
        format: double
        x-go-name: CpuUsagePercent
      instanceType:
        type: string
        x-go-name: InstanceType
      lastHeartbeatTime:
        type: string
        x-go-name: LastHeartbeatTime
      memoryUsagePercent:
        type: number
        format: double
        x-go-name: MemoryUsagePercent
      ready:
        type: string
        x-go-name: Ready
      storageUsagePercent:
        type: number
        format: double
        x-go-name: StorageUsagePercent
    x-go-package: github.com/banzaicloud/pipeline/internal/dashboard
