swagger: '2.0'
info:
  description: Pipeline v0.3.0 swagger
  version: "0.3.0"
  title: Pipeline Internal API
  contact:
    email: info@banzaicloud.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/notifications':
    get:
      description: Lists all notifications
      produces:
        - application/json
      schemes:
        - http
      operationId: GetNotifications
      responses:
        '200':
          description: GetNotificationsResponse
          schema:
            $ref: '#/definitions/GetNotificationsResponse'
  '/issues':
    post:
      description: Creates a new issue in the configured issue tracking system.
      schemes:
        - http
      operationId: CreateIssue
      parameters:
        - in: body
          name: user
          description: The issue to create.
          schema:
            type: object
            required:
              - organization
              - title
              - text
            properties:
              organization:
                type: string
              title:
                type: string
              text:
                type: string
              labels:
                type: array
                items:
                  type: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Issue Creation Failed
definitions:
  GetNotificationsResponse:
    description: GetNotificationsResponse Api object to be mapped to Get notifications request
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/MessagesResponse'
        x-go-name: Messages
    x-go-package: github.com/banzaicloud/pipeline/internal/notification
  MessagesResponse:
    type: object
    properties:
      id:
        type: integer
        x-go-name: Id
      message:
        type: string
        x-go-name: Message
      priority:
        description: Severity of the notifications
        type: integer
        x-go-name: Priority
    x-go-package: github.com/banzaicloud/pipeline/internal/notification
