version: 2
updates:
    - package-ecosystem: "gomod"
        # Files stored in repository root
      directory: "/"
      labels:
          - "dependencies"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 0

    - package-ecosystem: "docker"
      directory: "/"
      labels:
          - "dependencies"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 0

