run:
    skip-dirs:
        - .gen
        - client

    skip-files:
        - ".*_gen\\.go$"
        - "zz_generated\\..*\\.go$"

linters-settings:
    golint:
        min-confidence: 0.9
    gocyclo:
        min-complexity: 15
    goimports:
        local-prefixes: github.com/banzaicloud/pipeline

    depguard:
        list-type: blacklist
        include-go-root: false
        packages:
            - github.com/prometheus/common/log
        packages-with-error-messages:
            github.com/prometheus/common/log: "Global logger is deprecated. Inject a logger here. If you are trying to log in a function, chances are you should make it a struct."

linters:
    enable:
        - errcheck
        - staticcheck
        - deadcode
        - misspell
        - gofmt
        - golint
        - goimports
        - gochecknoglobals
        - depguard
    disable:
        - funlen
        - gas
        - megacheck
        - varcheck

        # Disable govet for now because it fails on Circle
        - govet

    fast: false
