run:
  skip-dirs:
    - client

linters-settings:
  golint:
    min-confidence: 0.9

  gocyclo:
    min-complexity: 15

linters:
  enable:
    - misspell
    - gofmt
    - golint
    - goimports
  disable:
    - errcheck
    - structcheck
    - gas
    - megacheck
    - varcheck
  fast: false
