run:
    skip-dirs:
        - .gen
        - client

linters-settings:
    golint:
        min-confidence: 0.9

    gocyclo:
        min-complexity: 15

linters:
    enable:
        - errcheck
        - staticcheck
        - deadcode
        - misspell
        - gofmt
        - golint
        - goimports
        - gochecknoglobals
    disable:
        - gas
        - megacheck
        - varcheck

        # Disable govet for now because it fails on Circle
        - govet

        # Doesn't work with Go 1.13
        - typecheck
    fast: false
