run:
    skip-dirs:
        - .gen
        - client

linters-settings:
    golint:
        min-confidence: 0.9
    gocyclo:
        min-complexity: 15
    goimports:
        local-prefixes: github.com/banzaicloud/pipeline

linters:
    enable:
        - errcheck
        - staticcheck
        - deadcode
        - misspell
        - gofmt
        - golint
        - goimports
        - gochecknoglobals
    disable:
        - funlen
        - gas
        - megacheck
        - varcheck

        # Disable govet for now because it fails on Circle
        - govet

    fast: false
