run:
    skip-dirs:
        - .gen
        - client

linters-settings:
    golint:
        min-confidence: 0.9

    gocyclo:
        min-complexity: 15

linters:
    enable:
        - misspell
        - gofmt
        - golint
        - goimports
        - gochecknoglobals
    disable:
        - errcheck
        - gas
        - megacheck
        - varcheck
    fast: false
