version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sparky
      MYSQL_USER: sparky
      MYSQL_PASSWORD: sparky123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
