// +build !ignore_autogenerated

// Code generated by mga tool. DO NOT EDIT.

package pkeaws

import (
	"context"
	"github.com/stretchr/testify/mock"
)

// MockImageSelector is an autogenerated mock for the ImageSelector type.
type MockImageSelector struct {
	mock.Mock
}

// SelectImage provides a mock function.
func (_m *MockImageSelector) SelectImage(ctx context.Context, criteria ImageSelectionCriteria) (_result_0 string, _result_1 error) {
	ret := _m.Called(ctx, criteria)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, ImageSelectionCriteria) string); ok {
		r0 = rf(ctx, criteria)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ImageSelectionCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
