/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pipeline

type NodePoolStatus struct {

	InstanceType string `json:"instanceType,omitempty"`

	SpotPrice string `json:"spotPrice,omitempty"`

	Autoscaling bool `json:"autoscaling,omitempty"`

	Count int32 `json:"count,omitempty"`

	MinCount int32 `json:"minCount,omitempty"`

	MaxCount int32 `json:"maxCount,omitempty"`

	Image string `json:"image,omitempty"`

	Labels map[string]string `json:"labels,omitempty"`

	ResourceSummary map[string]ResourceSummary `json:"resourceSummary,omitempty"`

	Ram int32 `json:"ram,omitempty"`

	Vcpu int32 `json:"vcpu,omitempty"`

	Template string `json:"template,omitempty"`
}

// AssertNodePoolStatusRequired checks if the required fields are not zero-ed
func AssertNodePoolStatusRequired(obj NodePoolStatus) error {
	return nil
}

// AssertRecurseNodePoolStatusRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NodePoolStatus (e.g. [][]NodePoolStatus), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNodePoolStatusRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNodePoolStatus, ok := obj.(NodePoolStatus)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNodePoolStatusRequired(aNodePoolStatus)
	})
}
