/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pipeline

type ScheduleResponse struct {

	Uid string `json:"uid,omitempty"`

	Name string `json:"name,omitempty"`

	Schedule string `json:"schedule,omitempty"`

	Ttl string `json:"ttl,omitempty"`

	Labels Labels `json:"labels,omitempty"`

	Options BackupOptions `json:"options,omitempty"`

	Status string `json:"status,omitempty"`

	LastBackup string `json:"lastBackup,omitempty"`
}

// AssertScheduleResponseRequired checks if the required fields are not zero-ed
func AssertScheduleResponseRequired(obj ScheduleResponse) error {
	if err := AssertLabelsRequired(obj.Labels); err != nil {
		return err
	}
	if err := AssertBackupOptionsRequired(obj.Options); err != nil {
		return err
	}
	return nil
}

// AssertRecurseScheduleResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ScheduleResponse (e.g. [][]ScheduleResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseScheduleResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aScheduleResponse, ok := obj.(ScheduleResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertScheduleResponseRequired(aScheduleResponse)
	})
}
