/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pipeline

type AmazonProviderConfig struct {

	AutoScalingGroup AmazonAutoScalingGroup `json:"autoScalingGroup"`
}

// AssertAmazonProviderConfigRequired checks if the required fields are not zero-ed
func AssertAmazonProviderConfigRequired(obj AmazonProviderConfig) error {
	elements := map[string]interface{}{
		"autoScalingGroup": obj.AutoScalingGroup,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertAmazonAutoScalingGroupRequired(obj.AutoScalingGroup); err != nil {
		return err
	}
	return nil
}

// AssertRecurseAmazonProviderConfigRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AmazonProviderConfig (e.g. [][]AmazonProviderConfig), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAmazonProviderConfigRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAmazonProviderConfig, ok := obj.(AmazonProviderConfig)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAmazonProviderConfigRequired(aAmazonProviderConfig)
	})
}
