/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pipeline

type CreateClusterRequestV2 struct {

	Name string `json:"name"`

	SecretId string `json:"secretId,omitempty"`

	SecretName string `json:"secretName,omitempty"`

	SshSecretId string `json:"sshSecretId,omitempty"`

	Type string `json:"type"`
}

// AssertCreateClusterRequestV2Required checks if the required fields are not zero-ed
func AssertCreateClusterRequestV2Required(obj CreateClusterRequestV2) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"type": obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCreateClusterRequestV2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateClusterRequestV2 (e.g. [][]CreateClusterRequestV2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateClusterRequestV2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateClusterRequestV2, ok := obj.(CreateClusterRequestV2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateClusterRequestV2Required(aCreateClusterRequestV2)
	})
}
