/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pipeline

type NodeItemStatusConditionsInner struct {

	Type string `json:"type,omitempty"`

	Status string `json:"status,omitempty"`

	LastHeartbeatTime string `json:"lastHeartbeatTime,omitempty"`

	LastTransitionTime string `json:"lastTransitionTime,omitempty"`

	Reason string `json:"reason,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertNodeItemStatusConditionsInnerRequired checks if the required fields are not zero-ed
func AssertNodeItemStatusConditionsInnerRequired(obj NodeItemStatusConditionsInner) error {
	return nil
}

// AssertRecurseNodeItemStatusConditionsInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NodeItemStatusConditionsInner (e.g. [][]NodeItemStatusConditionsInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNodeItemStatusConditionsInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNodeItemStatusConditionsInner, ok := obj.(NodeItemStatusConditionsInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNodeItemStatusConditionsInnerRequired(aNodeItemStatusConditionsInner)
	})
}
