/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pipeline

type OrganizationListItemResponse struct {

	Id int32 `json:"id,omitempty"`

	CreatedAt string `json:"createdAt,omitempty"`

	UpdatedAt string `json:"updatedAt,omitempty"`

	Name string `json:"name,omitempty"`

	NormalizedName string `json:"normalizedName,omitempty"`
}

// AssertOrganizationListItemResponseRequired checks if the required fields are not zero-ed
func AssertOrganizationListItemResponseRequired(obj OrganizationListItemResponse) error {
	return nil
}

// AssertRecurseOrganizationListItemResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OrganizationListItemResponse (e.g. [][]OrganizationListItemResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOrganizationListItemResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOrganizationListItemResponse, ok := obj.(OrganizationListItemResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOrganizationListItemResponseRequired(aOrganizationListItemResponse)
	})
}
