/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pipeline

type CreateGkePropertiesGkeMaster struct {

	Version string `json:"version,omitempty"`
}

// AssertCreateGkePropertiesGkeMasterRequired checks if the required fields are not zero-ed
func AssertCreateGkePropertiesGkeMasterRequired(obj CreateGkePropertiesGkeMaster) error {
	return nil
}

// AssertRecurseCreateGkePropertiesGkeMasterRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateGkePropertiesGkeMaster (e.g. [][]CreateGkePropertiesGkeMaster), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateGkePropertiesGkeMasterRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateGkePropertiesGkeMaster, ok := obj.(CreateGkePropertiesGkeMaster)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateGkePropertiesGkeMasterRequired(aCreateGkePropertiesGkeMaster)
	})
}
