/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pipeline

import (
	"time"
)

type ProcessEvent struct {

	Id int32 `json:"id,omitempty"`

	ProcessId string `json:"processId,omitempty"`

	Type string `json:"type,omitempty"`

	Log string `json:"log,omitempty"`

	Status ProcessStatus `json:"status,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`
}

// AssertProcessEventRequired checks if the required fields are not zero-ed
func AssertProcessEventRequired(obj ProcessEvent) error {
	return nil
}

// AssertRecurseProcessEventRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ProcessEvent (e.g. [][]ProcessEvent), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseProcessEventRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aProcessEvent, ok := obj.(ProcessEvent)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertProcessEventRequired(aProcessEvent)
	})
}
