log:
    level: "debug"
    format: "logfmt"

database:
    dialect: "mysql"
    host: "127.0.0.1"
    port: 3306
    tls: "false"
    user: "sparky"
    role: ""
    password: "sparky123"
    name: "pipeline"

    # Turn this to true to see all queries in the log
    queryLog: false

    autoMigrate: true

auth:
    oidc:
        issuer: "http://127.0.0.1:5556/dex"
        #        insecure: false
        clientId: "pipeline"
        clientSecret: "ZXhhbXBsZS1hcHAtc2VjcmV0"
    token:
        signingKey: "Th1s!sMyR4Nd0MStri4gPleaseChangeIt"
        issuer: "https://banzaicloud.com/"
        audience: "https://pipeline.banzaicloud.com"

cadence:
    host: "127.0.0.1"
    createNonexistentDomain: true
    workflowExecutionRetentionPeriodInDays: 3

cloudinfo:
    endpoint: "https://try.pipeline.banzai.cloud/cloudinfo/api/v1"
