subinclude("///pleasings2//go:compat")

filegroup(
    name = "processlog",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    visibility = ["PUBLIC"],
    deps = ["//pkg/sdk/brn"],
)
