subinclude("///pleasings2//go:compat")

filegroup(
    name = "clusterconfig",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    visibility = ["PUBLIC"],
    deps = [],
)
