subinclude("///pleasings2//openapi")

dex_version = "2.19.0"

remote_file(
    name = "spec",
    url = f"https://raw.githubusercontent.com/dexidp/dex/v{dex_version}/api/api.proto",
    hashes = ["018a987857b9130d4b8729231117a326233770e0a57e4b9cf7f1eb7c016383f9"],
    out = "apis/dex/api.proto",
    licences = ["Apache-2.0"],
)
