// Code generated by mockery v1.0.0. DO NOT EDIT.

package clusterfeaturedriver

import clusterfeature "github.com/banzaicloud/pipeline/internal/clusterfeature"
import context "context"
import mock "github.com/stretchr/testify/mock"

// MockFeatureService is an autogenerated mock type for the FeatureService type
type MockFeatureService struct {
	mock.Mock
}

// Activate provides a mock function with given fields: ctx, clusterID, featureName, spec
func (_m *MockFeatureService) Activate(ctx context.Context, clusterID uint, featureName string, spec map[string]interface{}) error {
	ret := _m.Called(ctx, clusterID, featureName, spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, clusterID, featureName, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Deactivate provides a mock function with given fields: ctx, clusterID, featureName
func (_m *MockFeatureService) Deactivate(ctx context.Context, clusterID uint, featureName string) error {
	ret := _m.Called(ctx, clusterID, featureName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, clusterID, featureName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Details provides a mock function with given fields: ctx, clusterID, featureName
func (_m *MockFeatureService) Details(ctx context.Context, clusterID uint, featureName string) (clusterfeature.Feature, error) {
	ret := _m.Called(ctx, clusterID, featureName)

	var r0 clusterfeature.Feature
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) clusterfeature.Feature); ok {
		r0 = rf(ctx, clusterID, featureName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clusterfeature.Feature)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = rf(ctx, clusterID, featureName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, clusterID
func (_m *MockFeatureService) List(ctx context.Context, clusterID uint) ([]clusterfeature.Feature, error) {
	ret := _m.Called(ctx, clusterID)

	var r0 []clusterfeature.Feature
	if rf, ok := ret.Get(0).(func(context.Context, uint) []clusterfeature.Feature); ok {
		r0 = rf(ctx, clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]clusterfeature.Feature)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, clusterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, clusterID, featureName, spec
func (_m *MockFeatureService) Update(ctx context.Context, clusterID uint, featureName string, spec map[string]interface{}) error {
	ret := _m.Called(ctx, clusterID, featureName, spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, clusterID, featureName, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
