dependencies:
- name: mysql
  version: 0.19.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mysql.enabled
- name: postgresql
  version: 3.18.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgres.enabled
  alias: postgres
- name: gcloud-sqlproxy
  version: 0.12.0
  repository: https://charts.rimusz.net
  condition: cloudsql.enabled
  alias: cloudsql