/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.12
 * Contact: nurmi@anchore.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anchore

import (
	"time"
)

// FeedGroupMetadata struct for FeedGroupMetadata
type FeedGroupMetadata struct {
	Name        string    `json:"name,omitempty"`
	CreatedAt   time.Time `json:"created_at,omitempty"`
	LastSync    time.Time `json:"last_sync,omitempty"`
	RecordCount int32     `json:"record_count,omitempty"`
}
