/*
Anchore Engine API Server

This is the Anchore Engine API. Provides the primary external API for users of the service.

API version: 0.1.20
Contact: nurmi@anchore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anchore

import (
	"encoding/json"
)

// RetrievedFile The retrieved file entry including content (b64 encoded)
type RetrievedFile struct {
	Path *string `json:"path,omitempty"`
	B64Content *string `json:"b64_content,omitempty"`
}

// NewRetrievedFile instantiates a new RetrievedFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetrievedFile() *RetrievedFile {
	this := RetrievedFile{}
	return &this
}

// NewRetrievedFileWithDefaults instantiates a new RetrievedFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetrievedFileWithDefaults() *RetrievedFile {
	this := RetrievedFile{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *RetrievedFile) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrievedFile) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *RetrievedFile) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *RetrievedFile) SetPath(v string) {
	o.Path = &v
}

// GetB64Content returns the B64Content field value if set, zero value otherwise.
func (o *RetrievedFile) GetB64Content() string {
	if o == nil || o.B64Content == nil {
		var ret string
		return ret
	}
	return *o.B64Content
}

// GetB64ContentOk returns a tuple with the B64Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetrievedFile) GetB64ContentOk() (*string, bool) {
	if o == nil || o.B64Content == nil {
		return nil, false
	}
	return o.B64Content, true
}

// HasB64Content returns a boolean if a field has been set.
func (o *RetrievedFile) HasB64Content() bool {
	if o != nil && o.B64Content != nil {
		return true
	}

	return false
}

// SetB64Content gets a reference to the given string and assigns it to the B64Content field.
func (o *RetrievedFile) SetB64Content(v string) {
	o.B64Content = &v
}

func (o RetrievedFile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.B64Content != nil {
		toSerialize["b64_content"] = o.B64Content
	}
	return json.Marshal(toSerialize)
}

type NullableRetrievedFile struct {
	value *RetrievedFile
	isSet bool
}

func (v NullableRetrievedFile) Get() *RetrievedFile {
	return v.value
}

func (v *NullableRetrievedFile) Set(val *RetrievedFile) {
	v.value = val
	v.isSet = true
}

func (v NullableRetrievedFile) IsSet() bool {
	return v.isSet
}

func (v *NullableRetrievedFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetrievedFile(val *RetrievedFile) *NullableRetrievedFile {
	return &NullableRetrievedFile{value: val, isSet: true}
}

func (v NullableRetrievedFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetrievedFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


