subinclude("///pleasings2//go:compat")

filegroup(
    name = "ack",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    visibility = ["PUBLIC"],
    deps = ["//pkg/errors"],
)
