subinclude("///pleasings2//go:compat")

go_library(
    name = "objectstore",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    visibility = ["PUBLIC"],
    deps = ["//pkg/objectstore"],
)
